backend:
  name: github
  repo: MatLukac/twccg
  branch: main

media_folder: "the-way/public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "the-way/public/articles"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Summary", name: "summary", widget: "text" }

      # Namiesto jedného markdown "body" pridáme modulárne sekcie:
      - label: "Content"
        name: "content"
        widget: "list"
        summary: "{{fields.type}} section"
        types:
          - label: "Text Block"
            name: "text"
            widget: "object"
            fields:
              - { label: "Text", name: "text", widget: "markdown" }

          - label: "Image"
            name: "image"
            widget: "object"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Alt text", name: "alt", widget: "string", required: false }
              - { label: "Caption", name: "caption", widget: "string", required: false }

          - label: "Quote"
            name: "quote"
            widget: "object"
            fields:
              - { label: "Quote", name: "quote", widget: "text" }
              - { label: "Author", name: "author", widget: "string", required: false }

          - label: "Gallery"
            name: "gallery"
            widget: "object"
            fields:
              - label: "Images"
                name: "images"
                widget: "list"
                field: { label: "Image", name: "image", widget: "image" }

