backend:
  name: github
  repo: MatLukac/twccg
  branch: main

media_folder: "the-way/public/images/uploads"
public_folder: "the-way/public/images/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "the-way/public/articles"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Author Image", name: "author_image", widget: "image", required: false }
      - { label: "Featured Image", name: "image", widget: "image", required: false, hint: "Titulný obrázok článku (zobrazí sa v zozname článkov)" }
      - { label: "Category", name: "category", widget: "string", required: false, hint: "Kategória článku (napr. Svätci, Stratégia, Príbehy)" }
      - { label: "Summary", name: "summary", widget: "text" }

      # Modular content sections
      - label: "Content"
        name: "content"
        widget: "list"
        summary: "{{fields.type}} section"
        types:
          - label: "Text Block"
            name: "text"
            widget: "object"
            fields:
              - { label: "Text", name: "text", widget: "markdown" }

          - label: "Image"
            name: "image"
            widget: "object"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Alt text", name: "alt", widget: "string", required: false }
              - { label: "Caption", name: "caption", widget: "string", required: false }
